# 第一阶段：构建环境
FROM thevlang/vlang:latest as builder

WORKDIR /app
COPY ./backend .

# 安装依赖并构建（适配 Alpine）
RUN apk add --no-cache \
    libatomic \
    musl-dev \
    mariadb-connector-c-dev \
    build-base && \
    v -prod -o app . && \
    rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

# 第二阶段：运行时环境
FROM thevlang/vlang:latest

WORKDIR /app

# 安装运行时依赖（Alpine）
RUN apk add --no-cache \
    libatomic \
    mariadb-connector-c && \
    rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

# 复制构建产物
COPY --from=builder /app/app .
COPY --from=builder /app/etc/ ./etc/


EXPOSE 9009
CMD ["./app", "-f", "etc/config.toml"]
