name: Forgejo Actions v-workspace
run-name: ${{ runner.actor }} is testing out Forgejo Actions 🚀
on:
  push:
    branches:
      - "main"
jobs:
  Deploy-Actions:
    runs-on: docker
    container:
      image: thevlang/vlang:alpine-dev
    steps:
      - name: Debug workspace
        run: |
          pwd
          ls -la /workspace
      - run: echo "🎉 The job was automatically triggered by a ${{ runner.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Forgejo!"
      - run: echo "🔎 The name of your branch is ${{ runner.ref }} and your repository is ${{ runner.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ runner.repository }} repository has been cloned to the runner."
      - name: Show workspace
        run: |
          pwd
          ls -la
          ls -la /workspace
      - run: echo "🖥️ The workflow is now ready to deploy your code on the runner."
      - name: Delete Container
        run: |
          docker rm -f v-admin
          docker rmi -f avey777/vadmin
      - name: Docker build
        run: |
          docker buildx build -f Dockerfile-docker -t avey777/vadmin .
      - name: Run Container
        run: |
          docker run --name=v-admin --restart=unless-stopped -p 9009:9009 -e CONFIG_PATH=backend/etc/config.toml -v /opt/vprod/config.toml:/workspace/vprod-admin/config.toml -d avey777/vprod-admin
      - name: Clean Docker cache
        run: |
          docker builder prune -f
      - run: echo "🍏 This job's status is ${{ job.status }}."
