[veb]
port = "0.0.0.0:9009"

[I18nConf]
Dir = "./internal/i18n"

# [DatabaseConf]
# Type = "mysql"
# Host = "127.0.0.1"
# DBname = "vprod"
# Port = "3306"
# Username = "root"
# Password = "mysql_123456"
# ssl-cert = ""

[DatabaseConf]
Type = "tidb"
Host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
DBname = "vprod"
Port = "4000"
Username = "xfQRtLXKTtPHsUi.root"
Password = "GkFU6Q3uvt0O9F0A"
# ssl-cert = "credentials/client-cert.pem"

[RedisConf]
Host = "127.0.0.1:6379"
# Host = "redis-server:6379" # docker连接配置
Db = 0

[Prometheus]
Host = "0.0.0.0"
Port = 4001
Path = "/metrics"

[log]
ServiceName = "coreRpcLogger"
Mode = "console"                  # file 是生产环境的配置，console 是开发环境的配置
Path = "/home/data/logs/core/rpc"
Encoding = "plain"                # plain 是开发环境的配置，json 是生产环境的配置
Level = "info"                    # info debug warn error fatal panic
Compress = false
KeepDays = 7
StackCoolDownMillis = 100


## TODO 请修改为自己的支付回调地址
[PayProperties]
OrderNotifyUrl = ""
RefundNotifyUrl = ""
OrderNoPrefix = "P"
RefundNoPrefix = "R"

## TODO 请修改为自己的支付宝配置
[AliPayConfig]
Status = false
AppId = ""
SignType = "RSA2"
PrivateKey = ""
AppPublicContentPath = "/cert/alipay/appPublicCert.crt"
AlipayPublicContentRSA2Path = "/cert/alipay/alipayPublicCert.crt"
AlipayRootContentPath = "/cert/alipay/alipayRootCert.crt"

## TODO 请修改为自己的微信支付配置
[WxPayConfig]
Status = false
AppId = ""
MchId = ""
SerialNumber = ""
ApiV3Key = ""
PrivateKeyContentPath = "/cert/wechat/apiclient_key.pem"
