name: Docker Push to Docker Hub
on:
  push:
    branches:
      - "main"

jobs:
  docker_push:
    if: startsWith(github.server_url, 'https://github.com')
    name: Build and Push Application with Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build Docker image
        run: |
          ./docker_build.sh

      - name: Push Docker image
        run: |
          ./docker_push.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  notification:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Pipeline status
        run: echo "🍏 This job's status is ${{ job.status }}."
