name: Forgejo Actions v-workspace
on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: thevlang/vlang:alpine-dev
    steps:
      - uses: actions/checkout@v4
      - name: Check V version
        run: v version
      - name: Install dependencies
        run: |
          apk add --no-cache mariadb-connector-c-dev
          # apk add --no-cache mariadb-connector-c-dev libatomic musl-dev build-base
      - name: Run tests
        working-directory: backend
        run: v -stats test .

  build:
    name: Build Application
    runs-on: ubuntu-latest
    container:
      image: thevlang/vlang:alpine-dev
    steps:
      - uses: actions/checkout@v4
      # - name: update v
      #   run: v up
      - name: Install dependencies
        run: |
          apk add --no-cache mariadb-connector-c-dev
          # apk add --no-cache mariadb-connector-c-dev libatomic musl-dev build-base
      - name: Build application
        working-directory: backend
        run: v -stats -cc gcc -o v-admin .

  notification:
    runs-on: docker
    if: always()
    steps:
      - name: Pipeline status
        run: echo "🍏 This job's status is ${{ job.status }}."
